### ISSUE TITLE
news: images layout

### ISSUE THREAD

**Issue by remi-dupre** [prologin/gcc-site#75]
Erk :nauseated_face: 

![Screenshot_2020-02-24 Dernières entrées – Girls Can Code ](https://user-images.githubusercontent.com/1173464/75144486-53bc9480-56f7-11ea-9c11-030b67db8f43.jpg)

**Comment by Elfikurr** [comment]
I believe it is because we do not use the "lead" section of the zinnia news entry.
We should add a "lead" paragraph to each news entry.
This will prevent the "content" paragraph from being displayed on the /news page.

Even when using the clear property, it looks bad D:

![DeepinScreenshot_select-area_20200405001850](https://user-images.githubusercontent.com/22329830/78462526-4bcb1980-76d3-11ea-8111-19a30cc8fbbc.png)


There may be a CSS fixing this though, I don't know much about CSS, so I don't know :')

**Comment by Elfikurr** [comment]
This is fixed by adding a lead paragraph.
